[supply_chain_servers]
; Replace <EC2_PUBLIC_IP> with the actual IP from terraform output
; ec2-host ansible_host=<EC2_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=../keys/supply-chain-dt-key.pem

[supply_chain_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
